name: flutter_todos
description: An example todos app that showcases bloc state management patterns.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  freezed_annotation: ^2.4.1
  get_it: ^7.7.0
  intl: ^0.18.0
  json_annotation: ^4.8.1
  local_storage_todos_api:
    path: packages/local_storage_todos_api
  riverpod_annotation: ^2.3.5
  todos_api:
    path: packages/todos_api
  todos_repository:
    path: packages/todos_repository
    

dev_dependencies:
  bloc_test: ^9.1.0
  build_runner: ^2.4.9
  custom_lint: ^0.6.4
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  json_serializable: ^6.7.1
  mockingjay: ^0.5.0
  mocktail: ^1.0.0
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10

flutter:
  uses-material-design: true
  generate: true
